<?php

$generos = Array('Afiches',
'Anécdotas',
'Artículos informativos',
'Blogs (entradas de blog)',
'Carta de presentación',
'Carta de solicitud u otras cartas a autoridades',
'Carta personal',
'Cartas',
'Cartas al director',
'Columnas de opinión',
'Comentarios breves a noticias en redes sociales',
'Comentarios sobre sus lecturas',
'Críticas',
'Cuentos',
'Diarios de vida',
'Ensayos',
'Experiencias personales',
'Historietas (cómic)',
'Informe de laboratorio',
'Informe de salida a un museo',
'Instrucciones',
'Libretos y diálogos ',
'Mensajes de redes sociales',
'Noticias',
'Poemas',
'Recaditos entre compañeros',
'Recados',
'Recados domésticos',
'Relatos de hechos',
'Reportes de una experiencia',
'Reseñas'
		);